FROM n8nio/n8n

# Accept build-time arguments
ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER
ARG USERNAME
ARG PASSWORD

# Set environment variables for database
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=${PGDATABASE}
ENV DB_POSTGRESDB_HOST=${PGHOST}
ENV DB_POSTGRESDB_PORT=${PGPORT}
ENV DB_POSTGRESDB_USER=${PGUSER}
ENV DB_POSTGRESDB_PASSWORD=${PGPASSWORD}

# Basic auth credentials
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${USERNAME}
ENV N8N_BASIC_AUTH_PASSWORD=${PASSWORD}

# Required for Railway or similar
ENV N8N_HOST=0.0.0.0
ENV PORT=5678
ENV N8N_PORT=5678
ENV N8N_EDITOR_BASE_URL=https://n8n-tecmac-bot-production.up.railway.app
ENV WEBHOOK_URL=https://n8n-tecmac-bot-production.up.railway.app

# Alpine networking optimization
ENV ENABLE_ALPINE_PRIVATE_NETWORKING=true

EXPOSE 5678

CMD ["n8n"]
